image: registry.gitlab.com/toastal/dhall-webmanifest

stages:
  - test

test:build:
  stage: test
  script: dhall --explain --file ./CSSColor/Color.dhall > /dev/null && echo "Build success!" && dhall --explain --file ./test/readme-test.dhall

test:license-banner:
  stage: test
  only:
    refs:
      - pushes
      - merge_requests
    changes:
      - "*.dhall"
      - "Webmanifest/**/*"
  script: ./test/run-license-banner.sh

badges:
  stage: .post
  only:
    - tags
  when: delayed
  start_in: 5 minutes
  script: ./bin/badges.fish
